# Works on both Linux and macOS
language: shell

script: tox

jobs:
  include:
    - name: "macOS"
      # From: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4

      addons:
        homebrew:
          packages:
          - python@2
          - shellcheck
          - tox

    - name: "Linux"
      os: linux
      dist: bionic

      addons:
        apt:
          packages:
          - tox
